{% set version = "0.3.0" %}

package:
  name: cachy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cachy/cachy-{{ version }}.tar.gz
  sha256: 186581f4ceb42a0bbe040c407da73c14092379b1e4c0e327fdb72ae4a9b269b1

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - cachy
    - cachy.contracts
    - cachy.serializers
    - cachy.stores

about:
  home: https://github.com/sdispater/cachy
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Cachy provides a simple yet effective caching library

extra:
  recipe-maintainers:
    - ocefpaf
