travis:
  secure:
    BINSTAR_TOKEN: 2ImOR2A9NgeN4vL+lnTikyoG55M5UvhxU0ZN8jDWqtlw9tXKCsoTkvy3A5xFy4OVeDDvsVOugoD8f/Rhzc9PsukPZicSHDfglBbwiOfrkDe68YyUqMSo2zmyXFAq9S1bYO7sw++FV4sW+Gp4qTFzS8hwse/MP8wbLujXE9wZy5zc3U2Kx+S6+3PZ+x7gEzxUNHhJT/S2V2ITVSAzOtNdzBkiia0/KmTKNI27DlZf+hntI5Rbbt6Yvz26kBitCWpC4k+PPdqqkxNtzfRdIu4EWB2hh5Y25VB5YzT37z29Xt4N1KiluEnqHBxwclopFEoYxKH2L6rMlCSGG8N+YxcjOII+XHKTEPO0cMWBWYkkUWTujsWPGgvtO5h/as7pGU5oN1fEK8yrHJKUMxFKTWdPrRiWH8kYNJe8NZApBNbDHY2NV31pT2/10RiM8P8TnkhlQbsSNHAvjohkDUVYnscOCmv98gist9uIlV7/wwYlqS7k0J/OsKarU9hBjFko+jFjAuZdMHqVt8ge8IWZ+uvCv2399CvGzkTcx7wehbowzEQEsJhCjhLRWrULdb2ERXWqkEFQoImHj7lMgUVa6ctCxCY66K9g8QJQRYmO+VfQz4uXFViQyBqojwBslPZB2qIItCTbuzb8ScLyT88M4+bOrNa9o1RLbkPIjX/zEC3Ltwc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
